
all:
	$(MAKE) all -C avakar_packet
	$(MAKE) all -C average
	$(MAKE) all -C fixedpoint_numbers
	$(MAKE) all -C packet
	$(MAKE) all -C value
	$(MAKE) all -C tagged

clean:
	$(MAKE) clean -C avakar_packet
	$(MAKE) clean -c average
	$(MAKE) clean -C fixedpoint_numbers
	$(MAKE) clean -C packet
	$(MAKE) clean -C value
	$(MAKE) clean -C tagged