
all:
	$(MAKE) all -C avakar_packet
	$(MAKE) all -C average
	$(MAKE) all -C packet
	$(MAKE) all -C value

clean:
	$(MAKE) clean -C avakar_packet
	$(MAKE) clean -c average
	$(MAKE) clean -C packet
	$(MAKE) clean -C value